parameters:
    fixture:
        path: '%kernel.project_dir%/data/fixtures'
    mailer:
        templateFolder: mail/
        senderAddress: noreply@music-one.com
        supportAddress: support@music-one.com
    media:
        repository: "%kernel.project_dir%/public/data"
        path: data/

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Event\DoctrinePasswordHasher:
        tags:
            - name: 'doctrine.event_subscriber'
